version: '3'

services:
  app:
    build: .
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - APP_KEY=1CslZJ9eQTYtDb7uY-8BWnTpZxb-KqK3
      - DB_CONNECTION=sqlite
    restart: always
